apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
---
apiVersion: v1
data:
  ssh_known_hosts: |-
    bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
    gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
    gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
    ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
    vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ssh_known_hosts":"bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==\ngithub.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==\ngitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=\ngitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf\ngitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9\nssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H\nvs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H\ngithub.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=\ngithub.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-ssh-known-hosts-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-ssh-known-hosts-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-ssh-known-hosts-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-ssh-known-hosts-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-tls-certs-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-tls-certs-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-tls-certs-cm
---
apiVersion: v1
data:
  admin.password: JDJhJDEwJFBFaFhPNlZ5OVhDWHBDT24wZkl3ZU9sOTBWaTdhQmhKVEJ6YVp6eE1hRkNvUElmLzVvSVJh
  admin.passwordMtime: MjAyMi0wNi0xMFQwNDo0ODo0NFo=
  server.secretkey: NmRkNmRPRFhwcGRsTnprYkVqQjNWNmQzVXY1TVlhbXdaVmFqby9yc09CVT0=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZakNDQWtxZ0F3SUJBZ0lRYzhFdW52M1N6ZllDMzhzUzFKckxBakFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFLRXdkQmNtZHZJRU5FTUI0WERUSXlNRFl4TURBME5ESXhPRm9YRFRJek1EWXhNREEwTkRJeApPRm93RWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUpwL3BLQ0hXWmYzRStnTlVsdWtscWlDK1pjU1BRdTFUSFFUOTQ1K2Rjb0VQbUM2NHRrQndUQTQKR0twV1hGUjE2SHNkWmRiZVpnMHZjWlFBK29mcVg4djlGNXJrZmhhUHR6Q2h6K0pCMU1TNWtSNjBUUmdNNUNNdwpvUElGTWdpWm5USDZJMFdGNWVkVUxFRUNIQ1VPa25vSkFzelN4YmlFT0FhdzdsSmpqVFd0dHNmSGRQZmJOdkdJCjAxNkVLQnZiUHpaa2VLR1FPS0ZMdTV2U0F2M3hzV1p4eEJCUVYxWFNuM3hyQnhHWXVJNkFlNmorYWZkdjc3ZGEKWGFpdG1WM3JXTk9wbjNlTWI1enVOUmEwOTQxcm1zNTg2YW51Z2dqaVZobW1paUFWUkoySlJzVnpodjA3bU5rOQp4b2FFdVYzcDZTTCtMaWxINTVaSU9ua3FSSHl3b3JFQ0F3RUFBYU9Cc3pDQnNEQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQjdCZ05WSFJFRWREQnkKZ2dsc2IyTmhiR2h2YzNTQ0RXRnlaMjlqWkMxelpYSjJaWEtDRkdGeVoyOWpaQzF6WlhKMlpYSXVZWEpuYjJOawpnaGhoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqWkM1emRtT0NKbUZ5WjI5alpDMXpaWEoyWlhJdVlYSm5iMk5rCkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQU94TCttYVpNdTMwOFQKOHNJN0I4WVo0SVc2c1B0UzZ1NXZoZUNhd1lnRlZvTlBaaHprc1IxZ2FTUk5xUTJUNkV3bFA0K1pmUGQxS2svNQp3TzdVV1hrSjN4cWY1VzEyZTFMUG10Wk1NazdZOE5aZlFLNHR6R1FwWXJMS25uUzY4STRnRmhWUDJaMXJyMEs1CkM0dXpuQ2FpdzY2T2lSZmFBTXdQb2Z2YTV5NFgzUDFZUUpMcGhwUjk4NTdrV3RXV29ybWlJVHNodzI0LzczckQKcmEwWTNqVW01eGJUeFNreW5mY1BBRGRsOElYK09LVU9Md1BKN2hoVXNYbmE4Q1drMFRTOEJUNlcxWnJuL3c0Swp4SEZnRzl1TXdWNmdSTVBLMXk3S1JpMFcvTlRaVXlhZ2U0SEhXNXR3VlNxWGQvNHhwN0szSWh1MFZ3TlN1cnFECjVxMmZuMzVaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbW4ra29JZFpsL2NUNkExU1c2U1dxSUw1bHhJOUM3Vk1kQlAzam41MXlnUStZTHJpCjJRSEJNRGdZcWxaY1ZIWG9leDFsMXQ1bURTOXhsQUQ2aCtwZnkvMFhtdVIrRm8rM01LSFA0a0hVeExtUkhyUk4KR0F6a0l6Q2c4Z1V5Q0ptZE1mb2pSWVhsNTFRc1FRSWNKUTZTZWdrQ3pOTEZ1SVE0QnJEdVVtT05OYTIyeDhkMAo5OXMyOFlqVFhvUW9HOXMvTm1SNG9aQTRvVXU3bTlJQy9mR3habkhFRUZCWFZkS2ZmR3NIRVppNGpvQjdxUDVwCjkyL3Z0MXBkcUsyWlhldFkwNm1mZDR4dm5PNDFGclQzald1YXpuenBxZTZDQ09KV0dhYUtJQlZFbllsR3hYT0cKL1R1WTJUM0dob1M1WGVucEl2NHVLVWZubGtnNmVTcEVmTENpc1FJREFRQUJBb0lCQUVMYjVCbFlHV3lMRHdGSAo2cEVnRzlhV3YzNGg5V3NBclRJNmhkSVRaZFBqbkQ3dUFVZFozQW1LN1JtaHY5a0pJVzlOM0lsc3V3c1BzZjRUCm9sZDVGTFhKTkJMaXVMSDR4WlQxSVdwUGhNMFJaUHk5bC9ORmVPREZwWkMyc04xSjVONEEyb3kya2pSV2w4UVcKTHFuV3NZckFKWWNQMjJLclRUZVFEOEoxdEdFNnZJYXNEcjVCalZjNFRmTHFvcGl1dWZKYmpMd0pxeUN0K0owMAp0TEV0UXlDKzZ4MUJhNEp6Qm92OGxQVFFNNE1BQnpEWkZvSTVURjN4dDczYUcxTTVoK1daQ1BBZkFORU5GNDlUCjQwTHFXYS9ESWZYdHJkdnZRZGM5eG9XVDRHREhqdFY1cUpabWxXNmY0UzlNbVpROWc1TnhuazJQa0p4ZHRGbVQKTEx2TVJVRUNnWUVBd2t6TkNMb0huWmN0UXdpa1ZTUFQvYjliRW9jaHRZMjUwd3ZYdnpWUHVMUzliS3NzS04rYQp6YUN1MmtjY1NGbXRNQStLNVF1amYwYzdFV2VxMkR1a0xkRUNzWFNxcXhTUkE0SGozd2Z6V2J3MWprVVN1aGxqCmdIRWpEZEJ5eXhuWXBYdXFFL1hHNGR2Q2JJaEpxSWhhaW5Qa1phRlFUaG9mM09YZklRQkIwV2tDZ1lFQXk0OUcKQkE0WGhKWElQYmtkZlFaZVZtZlpoWVRsTjc5UTNyalJ6TXczZE15VnU5NEU1ZGhOMFR4RFdOWXNpSEROTEhNOQpXUnplUjN1TzIrVnQ4VGxYaW50MmpVOGxyS3FLQTM5U0dNL2VsMHFVR2tiQ0ttK2JjMWlyT09nN2xReGNSL1B1CmZsSWFkZVg1WE9neTg3bXEyUjZhWXNoMEcvanYyQ0puVTFYdlZna0NnWUVBcEFTbkZGWE50ZmQzS3Q0eHN2bUMKcS9LTUU3RGxBTmk1NC9GY1Y3bk9LWExSY05seWRyS0RnRS9ES3RuYWd5eklhUWpGekNJdUMzUjY1VzlvcGc1Ngp3bjVzMHBaVXVBU3RnWk4xWThIWGFJbmJmOVRKUVRYTGJCS1ZiOFRtRXBNbjhsSFpPZTVBekVweDdxS0I0M1h2ClVHOFNmOFJVQVFwR21YZW5Dcm1uMWZrQ2dZQU41a09XcFV1dnp2WjBXSDZOK2ZCWklCQTNVTUxDRXJzMzZoRFIKVmlSM1FqejdMZ2JSbHZxQlRnY2ZPc2lockdvbUhkeFRpR2daSTNPMnlpeStxdmF5U3dubVRrQTVVUS9KZTFrawp2cFRwYWJ0QkxCRzRDaFRvUkdhMHBRN2tkNHFaa3l0MnpxNWwzSVV4ZGQxOHpQSEFqNWxsSTJEaVJCWkVnTnpqClVOdmQyUUtCZ0d6cVBjbkNOOFJCdmptR0pGd1huMUtzdVVFM3M5TndwMnozcDR2a1RQQ1FUMWoyeDJQNDNld1gKY2kyWHJ1ekR5dlRvaVpaR3IwTkpOL3pJVG5DL3NlQW5iM1VKU0dScmJXUTVabkd1YlRLVDFaYVFxRDlnWFdkZgpxaS9ybHArNVJOd0s4eWRhbnB6a2Z3SnloQkFxdlNZS2lJMUc3ZFY3RHowK2c0Y3lCeVYrCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
---
apiVersion: v1
data:
  password: Z2hwXzNDSWVFT0V0WjFsU1IyeVYwWHBPMzZxZHFrbUVVODM5VjFWaA==
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2ZveHV0ZWNoL2t1YmVybmV0ZXMuZ2l0
  username: Zm94dXRlY2g=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-3107838218
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: foxutech
spec: {}
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomizeapp
spec:
  destination:
    namespace: kustomize
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/base/
    repoURL: https://github.com/foxutech/kubernetes.git
    targetRevision: HEAD
status:
  health:
    status: Healthy
  history:
  - deployStartedAt: "2022-06-10T04:57:17Z"
    deployedAt: "2022-06-10T04:57:19Z"
    id: 0
    revision: 10bc25dab48280fbea8203db2b0ba98507293b25
    source:
      path: kustomize/base/
      repoURL: https://github.com/foxutech/kubernetes.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2022-06-10T04:57:19Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 10bc25dab48280fbea8203db2b0ba98507293b25
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2022-06-10T04:57:17Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/kustom-demo-app created
        name: kustom-demo-app
        namespace: kustomize
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/kustom-demo-app created
        name: kustom-demo-app
        namespace: kustomize
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 10bc25dab48280fbea8203db2b0ba98507293b25
      source:
        path: kustomize/base/
        repoURL: https://github.com/foxutech/kubernetes.git
        targetRevision: HEAD
  reconciledAt: "2022-06-10T04:57:19Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: kustom-demo-app
    namespace: kustomize
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: kustom-demo-app
    namespace: kustomize
    status: Synced
    version: v1
  sourceType: Kustomize
  summary:
    images:
    - nginx:latest
  sync:
    comparedTo:
      destination:
        namespace: kustomize
        server: https://kubernetes.default.svc
      source:
        path: kustomize/base/
        repoURL: https://github.com/foxutech/kubernetes.git
        targetRevision: HEAD
    revision: 10bc25dab48280fbea8203db2b0ba98507293b25
    status: Synced
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp
spec:
  destination:
    namespace: nodejstest
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/node-app/helm
    repoURL: https://github.com/foxutech/kubernetes.git
    targetRevision: HEAD
status:
  health:
    status: Progressing
  history:
  - deployStartedAt: "2022-06-10T04:46:22Z"
    deployedAt: "2022-06-10T04:46:24Z"
    id: 0
    revision: 10bc25dab48280fbea8203db2b0ba98507293b25
    source:
      path: argocd/node-app/helm
      repoURL: https://github.com/foxutech/kubernetes.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2022-06-10T04:46:24Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 10bc25dab48280fbea8203db2b0ba98507293b25
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2022-06-10T04:46:22Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/argoapptest created
        name: argoapptest
        namespace: nodejstest
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/argoapptest-app created
        name: argoapptest-app
        namespace: argoapptest
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/argoapptest-app created
        name: argoapptest-app
        namespace: argoapptest
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/gateway created
        name: gateway
        namespace: argoapptest
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 10bc25dab48280fbea8203db2b0ba98507293b25
      source:
        path: argocd/node-app/helm
        repoURL: https://github.com/foxutech/kubernetes.git
        targetRevision: HEAD
  reconciledAt: "2022-06-10T04:56:38Z"
  resources:
  - kind: Namespace
    name: argoapptest
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: argoapptest-app
    namespace: argoapptest
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: argoapptest-app
    namespace: argoapptest
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Progressing
    kind: Ingress
    name: gateway
    namespace: argoapptest
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://argocd-argoapptest.example.com/
    images:
    - motoskia/argo-app-1:v2
  sync:
    comparedTo:
      destination:
        namespace: nodejstest
        server: https://kubernetes.default.svc
      source:
        path: argocd/node-app/helm
        repoURL: https://github.com/foxutech/kubernetes.git
        targetRevision: HEAD
    revision: 10bc25dab48280fbea8203db2b0ba98507293b25
    status: Synced
---
