apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: argocd-backup-export
  namespace: argocd
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: argocd-export
            image: motoskia/argocdutil
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          serviceAccount: argocd-server
          serviceAccountName: argocd-server
